library(shiny)
library(descriptr, lib.loc = "C:/Users/HP/Documents/R/win-library")
library(olsrr, lib.loc = "C:/Users/HP/Documents/R/win-library"  )
library(inferr, lib.loc = "C:/Users/HP/Documents/R/win-library"  )
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(purrr)
library(tidyr)
library(tibble)

shinyServer(function(input, output, session) {

    source('logic/logic_modal.R', local = T)
    source('logic/logic_link.R', local = T)
    source('logic/logic_upload.R', local = T)
    source('logic/logic_transform2.R', local = T)
    source('logic/logic_view.R', local = T)
    source('logic/logic_screen.R', local = T)
    source('logic/logic_summary.R', local = T)
    source('logic/logic_freq_qual.R', local = T)
    source('logic/logic_cross.R', local = T)
    source('logic/logic_freq_quant.R', local = T)
    source('logic/logic_group_summary.R', local = T)
    source('logic/logic_mult1.R', local = T)
    source('logic/logic_mult2.R', local = T)
    source('logic/logic_binom.R', local = T)
    source('logic/logic_chisq.R', local = T)
    source('logic/logic_f.R', local = T)
    source('logic/logic_t.R', local = T)
    source('logic/logic_norm.R', local = T)
    source('logic/logic_bar.R', local = T)
    source('logic/logic_bar2.R', local = T)
    source('logic/logic_box.R', local = T)
    source('logic/logic_box2.R', local = T)
    source('logic/logic_hist.R', local = T)
    source('logic/logic_pie.R', local = T)
    source('logic/logic_pie3d.R', local = T)
    source('logic/logic_scatter.R', local = T)
    source('logic/logic_line.R', local = T)
    source('logic/logic_ttest.R', local = T)
    source('logic/logic_itest.R', local = T)
    source('logic/logic_ptest.R', local = T)
    source('logic/logic_binomtest.R', local = T)
    source('logic/logic_osvar.R', local = T)
    source('logic/logic_tsvar.R', local = T)
    source('logic/logic_osprop.R', local = T)
    source('logic/logic_tsprop.R', local = T)
    source('logic/logic_anova.R', local = T)
    source('logic/logic_levene.R', local = T)
    source('logic/logic_chigof.R', local = T)
    source('logic/logic_chict.R', local = T)
    source('logic/logic_cochran.R', local = T)
    source('logic/logic_runs.R', local = T)
    source('logic/logic_mcnemar.R', local = T)
    source('logic/logic_regress.R', local = T)
    source('logic/logic_mselection2.R', local = T)
    source('logic/logic_hetero.R', local = T)
    source('logic/logic_inflobs2.R', local = T)
    source('logic/logic_regdiag.R', local = T)
    source('logic/logic_regmisc.R', local = T)
    source('logic/logic_resdiagtrial.R', local = T)
    source('logic/logic_collin.R', local = T)
    source('logic/logic_mfit2.R', local = T)
    source('logic/logic_gscatter.R', local = T)
})
